---
- name: Ping windows server
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: false

  tasks:
    - name: Wait for target to become reachable
      ansible.builtin.wait_for_connection:
        timeout: 60

    - name: Gather facts
      ansible.builtin.setup:

    - name: Print facts
      ansible.builtin.debug:
        msg: "{{ hostvars[inventory_hostname] }}"

    - name: Get shares
      register: r_smb_info
      mgmt.windows.smb_info:
