---
- name: Ping windows server
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: false

  tasks:
    - name: Wait for target to become reachable
      ansible.builtin.wait_for_connection:
        timeout: 60

    - name: Gather facts
      ansible.builtin.setup:

    - name: Print facts
      ansible.builtin.debug:
        msg: "{{ hostvars[inventory_hostname] }}"

    - name: Get shares
      register: r_smb_shares
      ansible.windows.win_powershell:
        script: |
          $data = @{}
          $shares = Get-SmbShare

          $shares | ForEach-Object {
            $data.add($_.Name, @{})
            $data[$_.Name].add("metadata", $_)

            $access = Get-SmbShareAccess -Name $_.Name
            $data[$_.Name].add("access", $access)
          }

          Write-Host ($data | ConvertTo-Json)

    - name: Describe shares
      ansible.builtin.debug:
        msg: "{{ r_smb_shares.host_out | from_json }}"