---
- name: Gather VMWare Info
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Gather cluster info from given datacenter
      register: r_cluster_info
      community.vmware.vmware_cluster_info:
        datacenter: SDDC-Datacenter

    - name: Debug cluster info
      tags: debug
      ansible.builtin.debug:
        var: r_cluster_info

    - name: Gather information about all datacenters
      register: r_datacenter_info
      community.vmware.vmware_datacenter_info:

    - name: Debug datacenter info
      tags: debug
      ansible.builtin.debug:
        var: r_datacenter_info

    - name: Gather info for datastores
      register: r_datastore_info
      community.vmware.vmware_datastore_info:
        datacenter_name: SDDC-Datacenter

    - name: Debug datastore info
      tags: debug
      ansible.builtin.debug:
        var: r_datastore_info

    - name: Gather info for ESXi hosts
      register: r_host_facts
      loop: "{{ r_cluster_info.clusters['Cluster-1'].hosts }}"
      community.vmware.vmware_host_facts:
        esxi_hostname: "{{ item.name }}"
    
    - name: Debug host facts
      ansible.builtin.debug:
        var: r_host_facts

    - name: Gather all registered virtual machines
      register: r_guest_info
      community.vmware.vmware_vm_info:

    - name: Debug guest facts
      ansible.builtin.debug:
        var: r_guest_info